### ISSUE TITLE
Do You know how to remove assistant bar at all, not only buttons?

### ISSUE THREAD

**Issue by Monstrik** [don/KeyboardToolbarRemover#8] opened 2013-10-13 07:13 UTC

**Comment by don** [comment] 2013-10-15 15:40
Do you mean like the image in #9?

Are you using the latest code? As far as I know we fixed that with the changes for #7. If the latest code still does this please send me details so we can look into it.

**Comment by don** [comment] 2013-10-15 20:02
Duplicate of #9

**Closed as completed by don** 2013-10-15 20:02 UTC
